name: Release extension

on:
  workflow_dispatch:

env:
  FETCH_DEPTH: 0

jobs:
  # Build the extension on all platforms.
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            code-target: darwin-arm64

    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./editors/code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}

      # Install Node.
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install Node dependencies.
      - run: npm ci

      # Build the extension.
      - name: Package Extension (release)
        run: npx vsce unpublish --pat ${{ secrets.VSCE_PAT }} Posit.air-vscode
